### ISSUE TITLE
Funktioniert nicht mehr

### ISSUE THREAD

**Issue by 2terNick** [MathiasHun/FS22_IndoorCamFirst#2]
11.01.2024
Leider funktioniert das Script nicht mehr, modDesc auf 77 bzw. 79 erhöhen hat auch keinen Erfolg gebracht.
Kommt ein Fix für die neueste FS22 Version ?
Grüße  2terNik

**Comment by MathiasHun** [comment]
Hi, I'm using the latest FS22, no errors.
log.txt file gives an error, what are you experiencing? What is not working?
